### PR TITLE
Created a tracuser type and class 

### PR DESCRIPTION
**Pull request by standaloneSA**
There's no way I'm going to be able to scale with manually creating trac users, so I created the type and class to define them in puppet automatically. Note that the realm and the tracenv names must match, because the tracuser's .htpasswd path relies on it. 

Let me know if you have any questions! Thanks! 

--Matt

### CODE REVIEW

**Comment by eschiller** [comment]
Looks great, definitely a much needed feature to make this scale.

Now, if you were feeling ambitious, it might be worth having a "path" parameter you can optionally pass to the tracuser so that the default /trac/<tracname> path isn't mandatory with tracuser. This is super-useful as-is too though, so I'm gonna merge away. Thanks for contributing!

Love the blog by the way. The nagios post was a big help when I set up a monitoring system a couple years back.

**Comment by standaloneSA** [comment]
Oh, very cool :-) I'm glad I was able to help with the blog, thanks! And I'm glad you're digging these changes. There are some more things I'm probably going to add in (and I'll put the path in that list), but right now, I'm digging around in the actual trac source for a weird bug. 

You haven't come across an issue with comments and ticket update numbers showing up twice, on different comments, have you? I'm seeing something like, say, in a ticket, there can be a comment, #22 for instance. It can then show up again. Here's a screenshot: 

image

It's really strange. The source of Trac is twisty with all kinds of odd nooks and crannies, so it's taking me a while.  

Thanks for making this module, btw! I appreciate it! 

Take care, 

--Matt

**Comment by eschiller** [comment]
No, definitely haven't see repeat comments in Trac before. Is it possible it's the puppet module? What kind of DB are you using?

**Comment by standaloneSA** [comment]
It's a sqlite3 DB. We're going to try upgrading the machine to the newest release and see if it fixes it. It's very strange (esp since the comment IDs aren't stored in the DB, but are generated on the fly). 

Thanks anyway!

**Comment by eschiller** [comment]
I did notice that my exec creating the sqlite DB had a bug (running every time instead of just the first), so I just pushed a fix for that. If IDs are being generated on the fly, probably unrelated, but you never know....

**Pull request merged**
